### ISSUE TITLE
Cursor can reach invalid positions

### ISSUE THREAD

**Issue by Tossrock** [marijnz/unity-shell#1]
The text entry cursor can reach invalid positions pretty easily. Things that I've found triggering this:
- Backspacing beyond the start of the command then starts deleting the prompt. You can also backspace onto previous lines.
- Home can move the cursor to the beginning of the line, ie before `command >`
- Mouse select can enter invalid positions in multiple ways:
  - Single clicking in an invalid position on the same line is allowed (ie, within `command >`)
  - Single clicking from a valid cursor position to a position above the current line selects text from the start of the command (ie, directly after `command > `) up to the click position
  - Single clicking from an invalid cursor position can select arbitrary scrollback text
  - Double clicking a word selects it
  - etc

**Comment by marijnz** [comment]
I put in basic prevention for this, which should cover most of the cases you're describing. Let me know if there's still something fix-worthy, otherwise feel free to close this Issue.

https://github.com/marijnz/unity-shell/commit/3bc817e5baf871d30643a4c5666810f754fb0b0d

**Comment by Tossrock** [comment]
Tried it out, seems solid! Thanks for fixing this, makes the shell much more usable :)
