### ISSUE TITLE
Does not work on Unity 2020 versions

### ISSUE THREAD

**Issue by lulasz** [marijnz/unity-shell#15]
As title, looks amazing and very useful, but saddly I can't test it.

**Comment by slash-under** [comment]
Works here on Unity 2021.2.0. Just replace Mono.CSharp4.x.dll with a copy from a Unity editor install matching the target project.

Here's what worked here: `[Editor Path]\Editor\Data\MonoBleedingEdge\lib\mono\4.5\Mono.CSharp.dll`
