### ISSUE TITLE
Shell prints "invalid input" for certain valid inputs

### ISSUE THREAD

**Issue by Tossrock** [marijnz/unity-shell#2]
`Debug.Log("foo")` prints  `invalid input` in the shell window, but also successfully logs "foo" to the Unity console.
`var x = "hello"` also prints `invalid input`, but then accessing `x` yields the value of x.
Submitting the empty string also prints `invalid input`. Arguably it should just redraw the `command >` prompt.

**Comment by marijnz** [comment]
Thanks for going ahead and creating the PR for this! 👍
