### ISSUE TITLE
CS0246: namespace Mono could not be found...

### ISSUE THREAD

**Issue by hariedo** [marijnz/unity-shell#9]
I'm not sure if I'm doing something wrong or something broke. I updated to MacOS Unity 2018.2.1f1 and the latest shell today. I unchecked Editor on 3.5 and checked Editor on 4.0 platforms. Although inspector says this is not supported, it does seem to evaluate and manipulate the Unity world just fine. I get the above CS0246 error and cannot clear it, and any attempt to recompile any of the scripts seems to not complete due to the error.

**Comment by hariedo** [comment]
Okay, on MacOS, you have to specifically enable the preview/beta support for .NET 4.x scripts.

https://i.imgur.com/jzH2kO3.png

Found the answer on the "update edit" comment here:  https://stackoverflow.com/questions/42513782/why-cant-i-see-net-4-6-option-for-api-compatibility-level

**Comment by marijnz** [comment]
I updated the readme to make it to make "your Unity project is using the .NET 4.x runtime" more clear that this is something set in the Player Settings. Good?
